version: '3.8'

services:
  # YouSum Backend Application
  yousum-backend:
    build: .
    container_name: yousum-backend
    ports:
      - "8080:8080"
      - "8000:8000"
    environment:
      # ✅ AWS RDS MySQL 연결 설정 (RDS 사용으로 변경)
      - SPRING_DATASOURCE_URL=jdbc:mysql://${RDS_ENDPOINT:-yousum-mysql-db.cvaqg68u4xoh.ap-northeast-2.rds.amazonaws.com}:3306/yousum?useSSL=true&requireSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${RDS_USERNAME:-admin}
      - SPRING_DATASOURCE_PASSWORD=${RDS_PASSWORD:-12345678}
      
      # ===============================
      # AWS 설정 - 현재 주석처리됨
      # 로컬 파일 시스템 사용으로 변경
      # ===============================
      # - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      # - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      # - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME:-yousum-s3}
      # - AWS_REGION=${AWS_REGION:-ap-northeast-2}
      
      # OpenAI
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      
      # Google OAuth
      - GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}
      - GOOGLE_OAUTH_CLIENT_SECRET=${GOOGLE_OAUTH_CLIENT_SECRET}
      
      # YouTube API
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      
      # JWT
      - JWT_SECRET=${JWT_SECRET:-bXl2ZXJ5c2VjdXJld2l0aGxvbmdzZWNyZXRrZXlzdHJpbmcxMjM=}
      
      # Email
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
      
    # ✅ RDS 사용으로 로컬 MySQL 의존성 제거
    # depends_on:
    #   - mysql
    volumes:
      - ./logs:/app/logs
      - ./src/main/resources/textfiles:/app/textfiles  # 로컬 파일 시스템 마운트
      - /tmp:/tmp
    networks:
      - yousum-network
    restart: unless-stopped

  # ✅ RDS 사용으로 로컬 MySQL 컨테이너 비활성화
  # MySQL Database - RDS 사용으로 주석처리
  # mysql:
  #   image: mysql:8.0
  #   container_name: yousum-mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=yousum123!
  #     - MYSQL_DATABASE=yousum
  #     - MYSQL_USER=yousum
  #     - MYSQL_PASSWORD=yousum123!
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #     - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  #   command: --default-authentication-plugin=mysql_native_password
  #   networks:
  #     - yousum-network
  #   restart: unless-stopped

  # Redis (향후 캐싱용)
  redis:
    image: redis:7-alpine
    container_name: yousum-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - yousum-network
    restart: unless-stopped

volumes:
  # ✅ RDS 사용으로 로컬 MySQL 볼륨 비활성화
  # mysql_data:  # RDS 사용으로 주석처리
  redis_data:

networks:
  yousum-network:
    driver: bridge 