-- src/test/resources/schema.sql
-- H2 Database Schema for Testing

CREATE TABLE USER (
    USER_ID BIGINT PRIMARY KEY,
    USER_NAME VARCHAR(255),
    EMAIL VARCHAR(255) UNIQUE,
    PASSWORD VARCHAR(255),
    ROLE VARCHAR(255)
);

CREATE TABLE VIDEO (
    VIDEO_ID BIGINT PRIMARY KEY,
    YOUTUBE_ID VARCHAR(255) UNIQUE,
    TITLE VARCHAR(255),
    UPLOADER_NAME VARCHAR(255),
    ORIGINAL_URL VARCHAR(512),
    PUBLISHED_AT TIMESTAMP,
    ORIGINAL_LANGUAGE_CODE VARCHAR(255),
    DURATION_SECONDS INT,
    THUMBNAIL_URL TEXT,
    VIEW_COUNT BIGINT
);

CREATE TABLE SUMMARY (
    SUMMARY_ID BIGINT PRIMARY KEY,
    VIDEO_ID BIGINT,
    USER_ID BIGINT,
    CONTENT TEXT,
    TYPE VARCHAR(255),
    USER_PROMPT TEXT,
    CREATED_AT TIMESTAMP,
    LANGUAGE_CODE VARCHAR(255),
    FOREIGN KEY (VIDEO_ID) REFERENCES VIDEO(VIDEO_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
);

CREATE TABLE AUDIO_TRANSCRIPT (
    TRANSCRIPT_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    VIDEO_ID BIGINT,
    YOUTUBE_ID VARCHAR(255),
    TRANSCRIPT_PATH VARCHAR(255),
    CREATED_AT TIMESTAMP,
    FOREIGN KEY (VIDEO_ID) REFERENCES VIDEO(VIDEO_ID)
);


CREATE TABLE TAG (
    TAG_ID BIGINT PRIMARY KEY,
    TAG_NAME VARCHAR(255) UNIQUE
);

CREATE TABLE SUMMARY_ARCHIVE (
    ARCHIVE_ID BIGINT PRIMARY KEY,
    USER_ID BIGINT,
    SUMMARY_ID BIGINT,
    USER_NOTES TEXT,
    TITLE VARCHAR(255),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    LAST_VIEWED_AT TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
    FOREIGN KEY (SUMMARY_ID) REFERENCES SUMMARY(SUMMARY_ID)
);

CREATE TABLE SUMMARY_ARCHIVE_TAG (
    SUMMARY_ARCHIVE_ID BIGINT,
    TAG_ID BIGINT,
    PRIMARY KEY (SUMMARY_ARCHIVE_ID, TAG_ID),
    FOREIGN KEY (SUMMARY_ARCHIVE_ID) REFERENCES SUMMARY_ARCHIVE(ARCHIVE_ID),
    FOREIGN KEY (TAG_ID) REFERENCES TAG(TAG_ID)
);

CREATE TABLE QUIZ (
    QUIZ_ID BIGINT PRIMARY KEY,
    SUMMARY_ID BIGINT,
    CREATED_AT TIMESTAMP,
    FOREIGN KEY (SUMMARY_ID) REFERENCES SUMMARY(SUMMARY_ID)
);

CREATE TABLE QUESTION (
    QUESTION_ID BIGINT PRIMARY KEY,
    QUIZ_ID BIGINT,
    TEXT TEXT,
    FOREIGN KEY (QUIZ_ID) REFERENCES QUIZ(QUIZ_ID)
);

CREATE TABLE ANSWER_OPTION (
    OPTION_ID BIGINT PRIMARY KEY,
    QUESTION_ID BIGINT,
    TEXT TEXT,
    IS_CORRECT BOOLEAN,
    FOREIGN KEY (QUESTION_ID) REFERENCES QUESTION(QUESTION_ID)
);

CREATE TABLE VIDEO_RECOMMENDATION (
    RECOMMENDATION_ID BIGINT PRIMARY KEY,
    USER_ID BIGINT,
    VIDEO_ID BIGINT,
    REASON TEXT,
    CREATED_AT TIMESTAMP,
    IS_DELETED BOOLEAN,
    DELETED_AT TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
    FOREIGN KEY (VIDEO_ID) REFERENCES VIDEO(VIDEO_ID)
);

CREATE TABLE REMINDER (
    REMINDER_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID BIGINT,
    SUMMARY_ARCHIVE_ID BIGINT,
    REMINDER_TYPE VARCHAR(255),
    REMINDER_MESSAGE VARCHAR(255),
    REMINDER_TIME TIMESTAMP,
    IS_ACTIVE BOOLEAN,
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    FREQUENCY_INTERVAL INT,
    DAY_OF_WEEK INT,
    DAY_OF_MONTH INT,
    BASE_DATETIME_FOR_RECURRENCE TIMESTAMP,
    REMINDER_NOTE VARCHAR(255),
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
    FOREIGN KEY (SUMMARY_ARCHIVE_ID) REFERENCES SUMMARY_ARCHIVE(ARCHIVE_ID)
);

CREATE TABLE USER_ACTIVITY_LOG (
    LOG_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID BIGINT,
    ACTIVITY_TYPE VARCHAR(255),
    TARGET_ENTITY_TYPE VARCHAR(255),
    TARGET_ENTITY_ID_INT BIGINT,
    ACTIVITY_DETAIL VARCHAR(255),
    DETAILS TEXT,
    CREATED_AT TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
); 